name: flutter_application_2
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^0.13.3
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/club_logo.png
    - assets/4everknights.jpg
    - assets/AFROTC.jpg
    - assets/aiUCF-logo.png
    - assets/asa-logo.jpg
    - assets/asme-logo.png
    - assets/bajalogo.png
    - assets/esports-ucf.png
    - assets/fes-logo.jpg
    - assets/ieeelogo.png
    - assets/knightHacks-logo.png
    - assets/kxr-logo.png
    - assets/nsbelogo.png
    - assets/oSTEM-logo.png
    - assets/powerlifting-logo.png
    - assets/satellite-logo.png
    - assets/shpelogo.png
    - assets/ucfsports-image.jpg
    - assets/vrknightslogo.png
